# Generated by Django 5.1.3 on 2024-12-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='autosaloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dealerships.autosaloonmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Premium_Seller', 'Premium Seller'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Owner', 'Owner'), ('Dealer_Seller', 'Dealer Seller'), ('Dealer_Manager', 'Dealer Manager'), ('Dealer_Admin', 'Dealer Admin'), ('Dealer_Mechanic', 'Dealer Mechanic')], default='Seller', max_length=20),
        ),
    ]
