# Generated by Django 5.1.3 on 2024-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_autosaloon_alter_usermodel_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Premium_Seller', 'Premium Seller'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Owner', 'Owner')], default='Seller', max_length=20),
        ),
    ]
