# Generated by Django 5.1.3 on 2024-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosaloonmodel',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autosaloonmodel',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
