# Generated by Django 5.1.3 on 2024-11-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcar',
            old_name='title',
            new_name='model_car',
        ),
    ]
