# Generated by Django 5.1.3 on 2024-11-27 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_cars', '0002_rename_title_modelcar_model_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcar',
            name='brands',
        ),
        migrations.AddField(
            model_name='modelcar',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='dropout_cars.brandsmodel'),
            preserve_default=False,
        ),
    ]
