# Generated by Django 5.1.2 on 2024-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Premium_Seller', 'Premium Seller'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Owner', 'Owner')], default='Seller', max_length=20),
        ),
    ]
