# Generated by Django 5.1.2 on 2024-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_carsmodel_edit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='edit_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
