# Generated by Django 5.1.3 on 2024-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_carsmodel_photo_carphotomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='edit_count',
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
