# Generated by Django 5.1.2 on 2024-11-15 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], max_length=15)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'Suv'), ('crossover', 'Crossover'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup'), ('minivan', 'Minivan'), ('van', 'Van'), ('roadster', 'Roadster'), ('luxury car', 'Luxury Car'), ('sport car', 'Sport Car')], max_length=25)),
                ('engine', models.CharField(choices=[('inline', 'Inline'), ('v-type', 'V Type'), ('flat', 'Flat'), ('rotary', 'Rotary'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('diesel', 'Diesel'), ('turbocharged', 'Turbocharged'), ('supercharged', 'Supercharged'), ('w-type', 'W Type')], max_length=25)),
                ('eco_standard', models.CharField(choices=[('evro-6', 'Evro 6'), ('evro-5', 'Evro 5'), ('evro-4', 'Evro 4'), ('evro-3', 'Evro 3'), ('evro-2', 'Evro 2'), ('evro-1', 'Evro 1')], max_length=25)),
                ('checkpoint', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('tiptronic', 'Tiptronic'), ('robot', 'Robot'), ('variator', 'Variator')], max_length=25)),
                ('color', models.CharField(max_length=23)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('edit_required', 'Edit Required')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
