# Generated by Django 5.1.2 on 2024-11-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_carsmodel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
