# Generated by Django 5.1.3 on 2024-11-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_carsmodel_bad_words_alter_carsmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='bad_words',
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='inactive', max_length=20),
        ),
    ]
