# Generated by Django 5.1.2 on 2024-11-16 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_carsmodel_edit_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='brand',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='color',
            field=models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='edit_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='region',
            field=models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
