# Generated by Django 5.1.2 on 2024-11-16 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_carsmodel_brand_alter_carsmodel_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='brand',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s\\-]{1,49}$', 'Brand must start with an uppercase letter and can contain only letters, spaces, and dashes.')]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z0-9\\s\\-]{1,49}$', 'Model must start with an uppercase letter and can contain letters, numbers, spaces, and dashes.')]),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='region',
            field=models.CharField(max_length=23, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\-]{1,23}$', 'Region must consist of up to 23 characters and can include only letters, spaces, and dashes.')]),
        ),
    ]
