# Generated by Django 5.1.3 on 2024-11-17 17:32

from django.db import migrations, models

import apps.all_cars.listings.services


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_carsmodel_options_alter_carsmodel_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.all_cars.listings.services.CarsService.upload_car_photos),
        ),
    ]
