# Generated by Django 5.1.3 on 2024-11-17 19:04

import django.db.models.deletion
from django.db import migrations, models

import apps.all_cars.listings.services


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_carsmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='photo',
        ),
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to=apps.all_cars.listings.services.CarsService.upload_car_photos)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.carsmodel')),
            ],
            options={
                'db_table': 'car_photos',
            },
        ),
    ]
