# Generated by Django 5.1.3 on 2024-11-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_uah', models.DecimalField(decimal_places=4, max_digits=12)),
                ('eur_to_uah', models.DecimalField(decimal_places=4, max_digits=12)),
                ('usd_to_eur', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
    ]
