# Generated by Django 5.1.3 on 2024-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('role', models.CharField(
                    choices=[('Dealer_Seller', 'Dealer Seller'), ('Dealer_Manager', 'Dealer Manager'),
                             ('Dealer_Admin', 'Dealer Admin'), ('Dealer_Mechanic', 'Dealer Mechanic')],
                    default='Dealer_Admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

            ],
            options={
                'db_table': 'dealer_admin',
            },
        ),
    ]
