# Generated by Django 5.1.3 on 2024-12-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_carsmodel_autosaloon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsmodel',
            old_name='autosaloon',
            new_name='auto_saloon',
        ),
    ]
